# api specific parameters
parameters:
    integration:
        host:
            snt: '%snt_api_url%'
            snc: '%snc_api_url%'
        api_id:
            snt: 60747c620c56dddd926c2f0328fa760e
            snc: 6ab8946c9ec922ecba89385033689e94
        keys:
            snt: '%snt_signature_key%'
            snc: '%snc_signature_key%'
        urls:
            snt:
                login: '/auth/login'
                logout: '/auth/logout'
                jerarquia: '/integration/puntoatencion/jerarquia'
                recuperar_contrasena: '/auth/reset'
                modificar_contrasena: '/auth/modificar'
                validar_token: '/auth/validar'
                usuarios: '/usuarios'
                puntosatencion: '/integration/puntosatencion/ids'
            snc:
                login: '/auth/login'
                logout: '/auth/logout'
                recuperar_contrasena: '/auth/reset'
                modificar_contrasena: '/auth/modificar'
                validar_token: '/auth/validar'
                usuarios: '/usuarios'
                agentes: '/integracion/agentes'

